---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - food.github.com.reetas
  resources:
  - cakes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - food.github.com.reetas
  resources:
  - cakes/finalizers
  verbs:
  - update
- apiGroups:
  - food.github.com.reetas
  resources:
  - cakes/status
  verbs:
  - get
  - patch
  - update
